import type { EditorView } from "@codemirror/view";
import type { PDFDocumentLoadingTask, PDFDocumentProxy } from "pdfjs-dist/build/pdf.mjs";
import type { IndexeddbPersistence } from "y-indexeddb";
import type { WebsocketProvider } from "y-websocket";
import type * as Y from "yjs";
import type { ReviewItem } from "../shared/review.ts";
import type { BlameRun, CurrentUser, EditorSettings, ProjectFile, ProjectSummary } from "../shared/api-schema.ts";
import type { BuildDiagnostic } from "../shared/compile-errors.ts";

export type { BlameRun, CurrentUser, EditorSettings, ProjectFile, ProjectSummary };
export type GitFile = { index: string; worktree: string; path: string };
export type GitCommit = { shortId: string; author: string; date: string; subject: string };
export type GitState = { branch: string; dirty: boolean; files: GitFile[]; history: GitCommit[]; status?: string; conflict?: { branch: string } | null };
export type PdfBox = { page: number; left: number; top: number; width: number; height: number };
export type AppState = {
  activeFile: string; projectId: string; projects: ProjectSummary[]; user: CurrentUser | null; bootstrapReady: boolean;
  projectCanManage: boolean; projectCanEdit: boolean; accessShareId: string; git: GitState | null; main: string; files: ProjectFile[]; folders: string[];
  settings: EditorSettings | null; view: EditorView | null; doc: Y.Doc | null; provider: WebsocketProvider | null;
  persistence: IndexeddbPersistence | null; unsaved: boolean;
  readonly pdfDocument: PDFDocumentProxy | null; readonly pdfFitMode: "width" | "page"; readonly pdfRenderVersion: number;
  readonly pdfSourceRevision: string | null; readonly pdfZoom: number;
  filePreviewDocument: PDFDocumentProxy | null; filePreviewLoadingTask: PDFDocumentLoadingTask | null;
  filePreviewVersion: number; filePreviewZoom: number; reviewSelection: { from: number; to: number; selected: string } | null;
  selectionSuggestionIds: string[]; suggesting: boolean; toastTimer: ReturnType<typeof setTimeout> | null;
  compileDiagnostics: BuildDiagnostic[]; staticDiagnostics: BuildDiagnostic[];
};
export type DialogOptions = { title: string; label?: string; value?: string; maxLength?: number; message?: string; submitLabel: string; danger?: boolean; zip?: boolean; allowEmpty?: boolean; inputType?: "text" | "password" };
export type ReviewDecision = "accept" | "reject" | "resolve";
export type ReviewGroup = { id: string; path: string; kind: "comment" | "revision"; items: ReviewItem[] };
export type ShareDetails = { id: string; viewPath: string; editPath: string; agentPath: string; proposalAgentPath: string; clonePath: string };
export type ProjectMember = { username: string; role: string };
export type BuildInfo = { log: string; status?: string; pdf?: boolean; errors?: Array<{ path: string; line: number; message: string }>; stale?: boolean; sourceRevision?: string | null };
export type ProjectDetail = ProjectSummary & { main: string; files: ProjectFile[]; folders: string[]; settings: EditorSettings; build: BuildInfo; permissions?: { manage?: boolean; edit?: boolean; collaborate?: boolean } };
export type SourcePosition = { path: string; line: number; from?: number; to?: number };
export type PdfPosition = { page: number; x: number; y: number; revision: string; boxes?: PdfBox[] };
export type ReplacementPreview = { path: string; baseSha256: string; before: string; source: string };
export type SearchMatch = { path: string; line: number; from: number; to: number; text: string };
